/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashdisburser;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Nexo Bentola
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rst=null;
    public MainMenu() {
        initComponents();
        con=dbConnect.db_Con();
        lbl_admin.setText(String.valueOf(UserDetails.admin.toString()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        lbl_admin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        fund = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        update = new javax.swing.JButton();
        fund1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_admin.setFont(new java.awt.Font("Tekton Pro Cond", 0, 14)); // NOI18N
        lbl_admin.setForeground(new java.awt.Color(204, 153, 0));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 0));
        jLabel2.setText("Logged in as:");

        register.setText("Register User");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        fund.setText("Allocate Funds");
        fund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundActionPerformed(evt);
            }
        });

        Profile.setText("Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        update.setText("Update User");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        fund1.setText("Generate slip");
        fund1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fund1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Update User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Register User");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Allocate Funds");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem5.setText("Profile");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Profile");

        jMenuItem7.setText("Change Profile");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Reports");

        jMenuItem9.setText("Registered Users");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem11.setText("Allocated Funds");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem10.setText("Deleted Records");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Options");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem12.setText("Logout");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lbl_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(575, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fund1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fund, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Profile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(746, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fund, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(fund1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(lbl_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(534, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
            UserDetails.profile_id=UserDetails.id_admin;
            String role="admin";
            UserDetails.profile_role=role;
            UserDetails.profile_pwd=UserDetails.adminpwd;
            UserDetails.profile_usr=UserDetails.admin;
            Profile ad=new Profile();
            ad.setVisible(true);
      this.dispose();
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Wrong Id! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        

        }
    }//GEN-LAST:event_ProfileActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
       String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
        Update upde=new Update();
        upde.setVisible(true);
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong ID! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_updateActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
       String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
        Register reg=new Register();
        reg.setVisible(true);
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong ID! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void fundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundActionPerformed
        // TODO add your handling code here:
        String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
         AllocateFund af=new AllocateFund();
        af.setVisible(true);
        this.dispose();   
        }
        else{
            JOptionPane.showMessageDialog(null, "ID! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_fundActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
            Update ad=new Update();
            ad.setVisible(true);
      this.dispose();
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Wrong Id! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
            Register ad=new Register();
            ad.setVisible(true);
      this.dispose();
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Wrong Id! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        

        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
            AllocateFund ad=new AllocateFund();
            ad.setVisible(true);
      this.dispose();
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Wrong Id! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        

        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
            UserDetails.profile_id=UserDetails.id_admin;
            String role="admin";
            UserDetails.profile_role=role;
            UserDetails.profile_pwd=UserDetails.adminpwd;
            UserDetails.profile_usr=UserDetails.admin;
            Profile ad=new Profile();
            ad.setVisible(true);
      this.dispose();
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Wrong Id! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        

        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
         String x=JOptionPane.showInputDialog(null,"Confirm Admin ID","Validation",JOptionPane.WARNING_MESSAGE);
        String admin_pwd=String.valueOf(UserDetails.id_admin).toString();
        if(x.equals(admin_pwd))
        {
            UserDetails.profile_id=UserDetails.id_admin;
            String role="admin";
            UserDetails.profile_role=role;
            UserDetails.profile_pwd=UserDetails.adminpwd;
            UserDetails.profile_usr=UserDetails.admin;
            Profile ad=new Profile();
            ad.setVisible(true);
      this.dispose();
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Wrong Id! Try again","Validation",JOptionPane.ERROR_MESSAGE);
        

        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
      Login lg=new Login();
      lg.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        
        JFileChooser dialog=new JFileChooser();
        dialog.setSelectedFile(new File("Cash Disbursment deleted users Report"+".pdf"));
        int dRst=dialog.showSaveDialog(null);
        if(dRst==JFileChooser.APPROVE_OPTION){
        String filep=dialog.getSelectedFile().getPath();
        try{
              Document myDoc=new Document();
           PdfWriter myWriter=PdfWriter.getInstance(myDoc,new FileOutputStream(filep));
           
           PdfPTable table=new PdfPTable(11); 
           
           
           float[] col=new float[]{8,8,8,8,8,8,8,8,8,8,8};
           table.setWidths(col);
           table.setWidthPercentage(100);
           
           myDoc.open();
           myDoc.add(new Paragraph("Cash Disbursement",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.BLUE)));
           
           myDoc.add(new Paragraph(new Date().toString()));
           myDoc.add(new Paragraph("=========================================================================="));
           
           
          
           table.addCell(new PdfPCell(new Paragraph("User ID",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("National ID",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("First Name",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Middle Name",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Last Name",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           
           table.addCell(new PdfPCell(new Paragraph("Nation",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("County",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Sub County",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Ward",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           
            table.addCell(new PdfPCell(new Paragraph("Village",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Reason",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           
          
          String sel="select * from cash_deleted";
           pst=con.prepareStatement(sel);
           rst=pst.executeQuery();
           while(rst.next()){
            table.addCell(new PdfPCell(new Paragraph(rst.getString("user_id"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("national_id"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("first_name"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("middle_name"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("last_name"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("nation"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("county"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("sub_county"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("ward"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("village"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("reason"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            
           }
           myDoc.add(table);
           myDoc.close();    
           JOptionPane.showMessageDialog(null, "Report successfully generated","Report",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
        
        }          
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        
         JFileChooser dialog=new JFileChooser();
        dialog.setSelectedFile(new File("Cash Disbursment Registered users Report"+".pdf"));
        int dRst=dialog.showSaveDialog(null);
        if(dRst==JFileChooser.APPROVE_OPTION){
        String filep=dialog.getSelectedFile().getPath();
        try{
              Document myDoc=new Document();
           PdfWriter myWriter=PdfWriter.getInstance(myDoc,new FileOutputStream(filep));
           
           PdfPTable table=new PdfPTable(16); 
           
           
           float[] col=new float[]{8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8};
           table.setWidths(col);
           table.setWidthPercentage(100);
           
           myDoc.open();
           myDoc.add(new Paragraph("Cash Disbursement",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.BLUE)));
           
           myDoc.add(new Paragraph(new Date().toString()));
           myDoc.add(new Paragraph("=========================================================================="));
           
           
          
           table.addCell(new PdfPCell(new Paragraph("Id",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
          
           table.addCell(new PdfPCell(new Paragraph("First Name",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Middle Name",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Last Name",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("National ID",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Date of Birth",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Nation",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("County",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Sub County",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           
           table.addCell(new PdfPCell(new Paragraph("Sublocation",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Ward",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           
            table.addCell(new PdfPCell(new Paragraph("Village",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("Gender",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Marital Status",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Phone Number",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Address",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           
          
          String sel="select * from cash_users";
           pst=con.prepareStatement(sel);
           rst=pst.executeQuery();
           while(rst.next()){
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Id"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            
            table.addCell(new PdfPCell(new Paragraph(rst.getString("First_name"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Middle_name"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Last_name"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("National_id"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("DOB"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Nation"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("County"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Sub_county"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Sub_Location"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Ward"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Village"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Gender"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Marital_status"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Phone_number"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("Address"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           }
           myDoc.add(table);
           myDoc.close();    
           JOptionPane.showMessageDialog(null, "Report successfully generated","Report",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
        
        }          
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
         JFileChooser dialog=new JFileChooser();
        dialog.setSelectedFile(new File("Cash Disbursment Amount Allocated Report"+".pdf"));
        int dRst=dialog.showSaveDialog(null);
        if(dRst==JFileChooser.APPROVE_OPTION){
        String filep=dialog.getSelectedFile().getPath();
        try{
              Document myDoc=new Document();
           PdfWriter myWriter=PdfWriter.getInstance(myDoc,new FileOutputStream(filep));
           
           PdfPTable table=new PdfPTable(9); 
           
           
           float[] col=new float[]{8,8,8,8,8,8,8,8,8};
           table.setWidths(col);
           table.setWidthPercentage(100);
           
           myDoc.open();
           myDoc.add(new Paragraph("Cash Disbursement",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.BLUE)));
           
           myDoc.add(new Paragraph(new Date().toString()));
           myDoc.add(new Paragraph("=========================================================================="));
           
           
          
           table.addCell(new PdfPCell(new Paragraph("User Id",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("firstname",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("lastname",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("National ID",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Amount",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Bank Account",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Allocated by",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Date",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           table.addCell(new PdfPCell(new Paragraph("Time",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           
          
          String sel="select * from cash_useraccount";
           pst=con.prepareStatement(sel);
           rst=pst.executeQuery();
           while(rst.next()){
               table.addCell(new PdfPCell(new Paragraph(rst.getString("user_id"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
               table.addCell(new PdfPCell(new Paragraph(rst.getString("firstname"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
               table.addCell(new PdfPCell(new Paragraph(rst.getString("lastname"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
               table.addCell(new PdfPCell(new Paragraph(rst.getString("National_ID"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
               table.addCell(new PdfPCell(new Paragraph(rst.getString("amount"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("bank"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("allocator"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("date_allocated"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph(rst.getString("time_allocated"),FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.BOLD))));
           
           }
           myDoc.add(table);
           myDoc.close();    
           JOptionPane.showMessageDialog(null, "Report successfully generated","Report",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void fund1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fund1ActionPerformed
      Funds fd =new Funds();
      fd.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_fund1ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
     try{
             Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        
        
        
        int hr=cal.get(Calendar.HOUR);
        int min=cal.get(Calendar.MINUTE);
        int sec=cal.get(Calendar.SECOND);
        
           
         String inset="insert into cash_actionaudit(action,performed_by,user_id,affected_person,affected_id,date,time,role) values(?,?,?,?,?,?,?,?)";
                    pst=con.prepareStatement(inset);
                    pst.setString(1,"Logged out");
                    pst.setString(2,UserDetails.fuladm);
                    pst.setInt(3,UserDetails.id_admin);
                    pst.setString(4,"N/A");
                    pst.setString(5,"N/A");
                    pst.setString(6,day+"/"+(month+1)+"/"+year);
                    pst.setString(7,hr+":"+(min)+":"+sec);
                    pst.setString(8,"Audit");
                    pst.execute();
        Login lg=new Login();
        lg.setVisible(true);
        this.dispose();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       MainMenu mn=new MainMenu();
       mn.setDefaultCloseOperation(EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Profile;
    private javax.swing.JButton fund;
    private javax.swing.JButton fund1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lbl_admin;
    private javax.swing.JButton register;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
